/*
* Wire
* Copyright (C) 2016 Wire Swiss GmbH
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waz_call_MediaManager */

#ifndef _Included_com_waz_call_MediaManager
#define _Included_com_waz_call_MediaManager
#ifdef __cplusplus
extern "C" {
/*
 * Class:     com_waz_call_MediaManager
 * Method:    attach
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_com_waz_media_manager_MediaManager_attach
    (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif